owner: multiply-ai
repo: multiply-status-page

sites:
  - name: Multiply landing page
    url: https://multiply.ai
  - name: Multiply Launch API
    url: https://api.multiply.ai/api/health/
  - name: Multiply Launch Dashboard
    url: https://dashboard.multiply.ai/
  - name: Intelliflo IQ API
    url: https://intelliflo-api.multiply.ai/api/health/

status-website:
  cname: status.multiply.ai
  logoUrl: https://cdn.multiply.ai/emails/multiply_logo.png
  name: Multiply
  introTitle: "**Multiply** provides automated financial advice."
  introMessage: Check here for incidents and the status of Multiply's APIs and services
  navbar:
    - title: Status
      href: /
