owner: multiply-ai
repo: multiply-status-page

sites:
  - name: Multiply landing page
    url: https://multiply.ai
  - name: Irish Life Digital Advice
    url: https://digital-financial-advice.irishlife.ie
  - name: Multiply B2C App Backend
    url: https://user.multiply.ai/api/health/

status-website:
  cname: status.multiply.ai
  logoUrl: https://cdn.multiply.ai/emails/multiply_logo.png
  name: Multiply
  introTitle: "**Multiply** provides automated financial advice."
  introMessage: Check here for incidents and the status of Multiply's APIs and services
  navbar:
    - title: Status
      href: /
